'use client';
import {useEffect,useState} from 'react';
import {Copy,Save,ChevronLeft,ChevronRight} from 'lucide-react';
const clickTime=value=>value?new Date(value).toLocaleString():'—';
export default function TrackedLinks({api,postJson,role}){
 const [data,setData]=useState(null),[page,setPage]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;api('/api/tracked-links?page='+page).then(value=>{if(active)setData(value);}).catch(cause=>{if(active)setError(cause.message);});return()=>{active=false;};},[api,page]);
 async function run(task){setBusy(true);setError('');try{await task();setData(await api('/api/tracked-links?page='+page));}catch(cause){setError(cause.message);}finally{setBusy(false);}}
 function save(event){event.preventDefault();const form=event.currentTarget,values=new FormData(form);run(async()=>{await postJson('/api/tracked-links',{action:'create',name:values.get('name'),destination:values.get('destination'),expiresDays:Number(values.get('expiresDays')),enabled:values.get('enabled')==='on'});form.reset();});}
 return <section className="trackedLinks"><h3>Campaign link tracking</h3>{role==='Owner'&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><div className="wa-ad-grid"><label>Name<input name="name" required maxLength={120}/></label><label>Destination<input name="destination" type="url" required maxLength={2000}/></label><label>Expiration days<input name="expiresDays" type="number" required min="1" max="365"/></label><label className="checkRow"><input name="enabled" type="checkbox"/>Enabled</label></div><button type="submit"><Save size={16}/>Create link</button></fieldset></form>}
 {error&&<p role="alert">{error}</p>}<div className="wa-module-table"><table><thead><tr><th>Name</th><th>Destination</th><th>Click metrics</th><th>First / last click</th><th>Actions</th></tr></thead><tbody>{data?.links.map(link=><tr key={link.id}><td>{link.name}<small>{link.enabled?'Enabled':'Disabled'}</small></td><td style={{overflowWrap:'anywhere'}}>{link.destination}</td><td><strong>{link.total_clicks}</strong> total<small>{link.unique_clickers} unique clickers · {link.issued_links} issued</small>{link.slotBreakdown?.length>0&&<ul>{link.slotBreakdown.map(slot=><li key={slot.slot}><small>{slot.slot}: {slot.totalClicks} total, {slot.uniqueClickers} unique / {slot.issuedLinks} issued</small></li>)}</ul>}</td><td><small>First: {clickTime(link.first_clicked_at)}<br/>Last: {clickTime(link.last_clicked_at)}</small></td><td><div className="wa-module-controls"><button type="button" title="Copy body parameter reference" aria-label="Copy body parameter reference" onClick={()=>run(()=>navigator.clipboard.writeText(link.marker))}><Copy size={16}/>Body</button><button type="button" title="Copy tracked URL button reference" aria-label="Copy tracked URL button reference" onClick={()=>run(()=>navigator.clipboard.writeText(link.tokenMarker))}><Copy size={16}/>URL</button>{role==='Owner'&&<label className="checkRow"><input type="checkbox" checked={link.enabled} disabled={busy} onChange={event=>run(()=>postJson('/api/tracked-links',{action:'toggle',id:link.id,enabled:event.target.checked}))}/>Enabled</label>}</div></td></tr>)}</tbody></table></div>
 {data&&!data.links.length&&<p>No tracking destinations configured.</p>}<div className="wa-module-controls"><button type="button" title="Previous links" aria-label="Previous links" disabled={page===1||busy} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/></button><span>{page}</span><button type="button" title="Next links" aria-label="Next links" disabled={!data?.hasMore||busy} onClick={()=>setPage(page+1)}><ChevronRight size={16}/></button></div></section>;
}
